spring.application.name=subscription-service
spring.data.mongodb.uri=mongodb://localhost:27017/subscriptiondb


#spring.security.user.name=admin
#spring.security.user.password=admin
logging.level.org.springframework.security=DEBUG